// GENERATED SDK for license/windows API

import {Client} from '../client'
import QueryParams from '../query-params'

/*
 * A short description of what does the Task on your license
 */
export enum LicenseActionType {
  ADDWINDOWFROMEXISTINGSERIAL = 'addWindowFromExistingSerial',
  CHANGEIP = 'changeIp',
  CHANGEOS = 'changeOs',
  INSTALLLICENSE = 'installLicense',
  OPTIONUPGRADE = 'optionUpgrade',
  RELEASEOPTION = 'releaseOption',
  VERSIONUPGRADE = 'versionUpgrade'
}

/*
 * Possible values for license type
 */
export enum LicenseLicenseType {
  DEDICATED = 'dedicated',
  DEDICATEDCLOUD = 'dedicatedCloud',
  DEDICATEDFAILOVER = 'dedicatedFailover',
  FAILOVER = 'failover',
  VM = 'vm',
  VPS = 'vps',
  VPS_CEPH = 'vps_ceph',
  VPS_CLASSIC = 'vps_classic',
  VPS_CLOUD = 'vps_cloud',
  VPS_CLOUD_2016 = 'vps_cloud_2016',
  VPS_SSD = 'vps_ssd'
}

/**
 * Your License options
 */
export interface LicenseOption {
  amount?: string
  canBeDeleted: boolean
  expirationDate: string
  label: LicenseOptionLabel
  version?: string
}

/*
 * The name of an option currently enabled on your license
 */
export enum LicenseOptionLabel {
  ANTISPAM_SPAMASSASSIN = 'ANTISPAM_SPAMASSASSIN',
  ANTIVIRUS_DRWEB = 'ANTIVIRUS_DRWEB',
  ANTIVIRUS_KASPERSKY = 'ANTIVIRUS_KASPERSKY',
  DOMAINS = 'DOMAINS',
  LANGUAGE_PACK = 'LANGUAGE_PACK',
  POWERPACK = 'POWERPACK',
  SQL_SERVER = 'SQL_SERVER',
  VIRTUOZZO_CONTAINERS = 'VIRTUOZZO_CONTAINERS'
}

/**
 * All SQL options available for Windows products
 */
export interface LicenseOrderableWindowsCompatibilityInfos {
  compliantSql: LicenseWindowsSqlVersionEnum[]
  version: LicenseWindowsOsVersion
}

/*
 * All states a license can be in
 */
export enum LicenseState {
  OK = 'ok',
  RELEASED = 'released',
  TERMINATED = 'terminated',
  TODELIVER = 'toDeliver'
}

/**
 * licenses Todos
 */
export interface LicenseTask {
  action: LicenseActionType
  doneDate?: string
  lastUpdate: string
  name: string
  status: LicenseTaskState
  taskId: number
  todoDate: string
}

/*
 * All states a license Task can be in
 */
export enum LicenseTaskState {
  CANCELLED = 'cancelled',
  DOING = 'doing',
  DONE = 'done',
  ERROR = 'error',
  TODO = 'todo'
}

/**
 * Your Windows license
 */
export interface LicensewindowsWindows {
  creation: string
  deleteAtExpiration: boolean
  domain: string
  ip: string
  licenseId: string
  status: LicenseState
  version: LicenseWindowsOsVersion
}

/**
 * Allowed windows versions and their compliant options per matching serviceTypes
 */
export interface LicenseWindowsOrderConfiguration {
  orderableVersions: LicenseOrderableWindowsCompatibilityInfos[]
  serviceType: LicenseLicenseType
}

/*
 * All versions for Windows products
 */
export enum LicenseWindowsOsVersion {
  WINDOWS_SERVER_2003_ENTERPRISE_EDITION = 'WINDOWS_SERVER_2003_ENTERPRISE_EDITION',
  WINDOWS_SERVER_2003_ENTERPRISE_EDITION_2_CPU = 'WINDOWS_SERVER_2003_ENTERPRISE_EDITION_2_CPU',
  WINDOWS_SERVER_2003_STANDARD_EDITION = 'WINDOWS_SERVER_2003_STANDARD_EDITION',
  WINDOWS_SERVER_2003_WEB_EDITION = 'WINDOWS_SERVER_2003_WEB_EDITION',
  WINDOWS_SERVER_2003_WEB_EDITION_2_CPU = 'WINDOWS_SERVER_2003_WEB_EDITION_2_CPU',
  WINDOWS_SERVER_2003_WEB_ENHANCED_EDITION = 'WINDOWS_SERVER_2003_WEB_ENHANCED_EDITION',
  WINDOWS_SERVER_2003_WEB_STANDARD_EDITION = 'WINDOWS_SERVER_2003_WEB_STANDARD_EDITION',
  WINDOWS_SERVER_2003_WEB_STANDARD_EDITION_2_CPU = 'WINDOWS_SERVER_2003_WEB_STANDARD_EDITION_2_CPU',
  WINDOWS_SERVER_2008_DATACENTER_EDITION = 'WINDOWS_SERVER_2008_DATACENTER_EDITION',
  WINDOWS_SERVER_2008_DATACENTER_EDITION_2_CPU = 'WINDOWS_SERVER_2008_DATACENTER_EDITION_2_CPU',
  WINDOWS_SERVER_2008_DATACENTER_EDITION_4_CPU = 'WINDOWS_SERVER_2008_DATACENTER_EDITION_4_CPU',
  WINDOWS_SERVER_2008_ENTERPRISE_EDITION = 'WINDOWS_SERVER_2008_ENTERPRISE_EDITION',
  WINDOWS_SERVER_2008_ENTERPRISE_EDITION_2_CPU = 'WINDOWS_SERVER_2008_ENTERPRISE_EDITION_2_CPU',
  WINDOWS_SERVER_2008_ENTERPRISE_EDITION_4_CPU = 'WINDOWS_SERVER_2008_ENTERPRISE_EDITION_4_CPU',
  WINDOWS_SERVER_2008_STANDARD_EDITION = 'WINDOWS_SERVER_2008_STANDARD_EDITION',
  WINDOWS_SERVER_2008_STANDARD_EDITION_2_CPU = 'WINDOWS_SERVER_2008_STANDARD_EDITION_2_CPU',
  WINDOWS_SERVER_2008_STANDARD_EDITION_4_CPU = 'WINDOWS_SERVER_2008_STANDARD_EDITION_4_CPU',
  WINDOWS_SERVER_2008_WEB_EDITION = 'WINDOWS_SERVER_2008_WEB_EDITION',
  WINDOWS_SERVER_2008_WEB_EDITION_2_CPU = 'WINDOWS_SERVER_2008_WEB_EDITION_2_CPU',
  WINDOWS_SERVER_2008_WEB_EDITION_4_CPU = 'WINDOWS_SERVER_2008_WEB_EDITION_4_CPU',
  WINDOWS_SERVER_2008_WEB_STANDARD_EDITION = 'WINDOWS_SERVER_2008_WEB_STANDARD_EDITION',
  WINDOWS_SERVER_2012_DATACENTER_EDITION = 'WINDOWS_SERVER_2012_DATACENTER_EDITION',
  WINDOWS_SERVER_2012_DATACENTER_EDITION_2_CPU = 'WINDOWS_SERVER_2012_DATACENTER_EDITION_2_CPU',
  WINDOWS_SERVER_2012_DATACENTER_EDITION_4_CPU = 'WINDOWS_SERVER_2012_DATACENTER_EDITION_4_CPU',
  WINDOWS_SERVER_2012_ENTERPRISE_EDITION = 'WINDOWS_SERVER_2012_ENTERPRISE_EDITION',
  WINDOWS_SERVER_2012_ENTERPRISE_EDITION_2_CPU = 'WINDOWS_SERVER_2012_ENTERPRISE_EDITION_2_CPU',
  WINDOWS_SERVER_2012_STANDARD_EDITION = 'WINDOWS_SERVER_2012_STANDARD_EDITION',
  WINDOWS_SERVER_2012_STANDARD_EDITION_2_CPU = 'WINDOWS_SERVER_2012_STANDARD_EDITION_2_CPU',
  WINDOWS_SERVER_2012_STANDARD_EDITION_4_CPU = 'WINDOWS_SERVER_2012_STANDARD_EDITION_4_CPU',
  WINDOWS_SERVER_2012_WEB_EDITION = 'WINDOWS_SERVER_2012_WEB_EDITION',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_10_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_10_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_12_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_12_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_14_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_14_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_16_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_16_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_18_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_18_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_20_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_20_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_22_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_22_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_24_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_24_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_8_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_1_CPU_8_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_10_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_10_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_12_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_12_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_14_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_14_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_16_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_16_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_18_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_18_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_20_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_20_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_22_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_22_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_24_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_24_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_8_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_2_CPU_8_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_10_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_10_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_12_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_12_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_14_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_14_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_16_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_16_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_18_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_18_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_20_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_20_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_22_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_22_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_24_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_24_CORES',
  WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_8_CORES = 'WINDOWS_SERVER_2016_DATACENTER_EDITION_4_CPU_8_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_10_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_10_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_12_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_12_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_14_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_14_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_16_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_16_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_18_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_18_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_20_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_20_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_22_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_22_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_24_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_24_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_8_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_1_CPU_8_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_10_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_10_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_12_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_12_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_14_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_14_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_16_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_16_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_18_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_18_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_20_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_20_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_22_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_22_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_24_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_24_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_8_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_2_CPU_8_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_10_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_10_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_12_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_12_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_14_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_14_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_16_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_16_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_18_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_18_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_20_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_20_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_22_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_22_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_24_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_24_CORES',
  WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_8_CORES = 'WINDOWS_SERVER_2016_STANDARD_EDITION_4_CPU_8_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_10_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_10_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_12_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_12_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_14_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_14_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_16_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_16_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_18_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_18_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_20_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_20_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_22_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_22_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_24_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_24_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_26_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_26_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_28_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_28_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_30_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_30_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_32_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_32_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_34_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_34_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_36_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_36_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_38_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_38_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_40_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_40_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_42_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_42_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_44_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_44_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_46_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_46_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_48_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_48_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_50_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_50_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_52_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_52_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_54_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_54_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_56_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_56_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_58_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_58_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_60_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_60_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_62_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_62_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_64_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_64_CORES',
  WINDOWS_SERVER_2019_DATACENTER_EDITION_8_CORES = 'WINDOWS_SERVER_2019_DATACENTER_EDITION_8_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_10_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_10_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_12_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_12_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_14_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_14_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_16_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_16_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_18_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_18_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_20_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_20_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_22_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_22_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_24_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_24_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_26_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_26_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_28_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_28_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_30_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_30_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_32_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_32_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_34_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_34_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_36_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_36_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_38_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_38_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_40_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_40_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_42_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_42_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_44_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_44_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_46_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_46_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_48_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_48_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_50_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_50_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_52_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_52_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_54_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_54_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_56_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_56_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_58_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_58_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_60_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_60_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_62_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_62_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_64_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_64_CORES',
  WINDOWS_SERVER_2019_STANDARD_EDITION_8_CORES = 'WINDOWS_SERVER_2019_STANDARD_EDITION_8_CORES',
  WINDOWS_SERVER_2008_LICENSE_DATACENTER_EDITION_1_CPU = 'windows-server-2008-license-datacenter-edition-1-cpu',
  WINDOWS_SERVER_2008_LICENSE_DATACENTER_EDITION_2_CPU = 'windows-server-2008-license-datacenter-edition-2-cpu',
  WINDOWS_SERVER_2008_LICENSE_DATACENTER_EDITION_4_CPU = 'windows-server-2008-license-datacenter-edition-4-cpu',
  WINDOWS_SERVER_2008_LICENSE_ENTERPRISE_EDITION_1_CPU = 'windows-server-2008-license-enterprise-edition-1-cpu',
  WINDOWS_SERVER_2008_LICENSE_ENTERPRISE_EDITION_2_CPU = 'windows-server-2008-license-enterprise-edition-2-cpu',
  WINDOWS_SERVER_2008_LICENSE_ENTERPRISE_EDITION_4_CPU = 'windows-server-2008-license-enterprise-edition-4-cpu',
  WINDOWS_SERVER_2008_LICENSE_STANDARD_EDITION_1_CPU = 'windows-server-2008-license-standard-edition-1-cpu',
  WINDOWS_SERVER_2008_LICENSE_STANDARD_EDITION_2_CPU = 'windows-server-2008-license-standard-edition-2-cpu',
  WINDOWS_SERVER_2008_LICENSE_STANDARD_EDITION_4_CPU = 'windows-server-2008-license-standard-edition-4-cpu',
  WINDOWS_SERVER_2008_LICENSE_WEB_EDITION_1_CPU = 'windows-server-2008-license-web-edition-1-cpu',
  WINDOWS_SERVER_2008_LICENSE_WEB_EDITION_2_CPU = 'windows-server-2008-license-web-edition-2-cpu',
  WINDOWS_SERVER_2008_LICENSE_WEB_EDITION_4_CPU = 'windows-server-2008-license-web-edition-4-cpu',
  WINDOWS_SERVER_2012_LICENSE_DATACENTER_EDITION_1_CPU = 'windows-server-2012-license-datacenter-edition-1-cpu',
  WINDOWS_SERVER_2012_LICENSE_DATACENTER_EDITION_2_CPU = 'windows-server-2012-license-datacenter-edition-2-cpu',
  WINDOWS_SERVER_2012_LICENSE_DATACENTER_EDITION_4_CPU = 'windows-server-2012-license-datacenter-edition-4-cpu',
  WINDOWS_SERVER_2012_LICENSE_STANDARD_EDITION_1_CPU = 'windows-server-2012-license-standard-edition-1-cpu',
  WINDOWS_SERVER_2012_LICENSE_STANDARD_EDITION_2_CPU = 'windows-server-2012-license-standard-edition-2-cpu',
  WINDOWS_SERVER_2012_LICENSE_STANDARD_EDITION_4_CPU = 'windows-server-2012-license-standard-edition-4-cpu',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_10_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-10-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_12_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-12-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_14_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-14-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_16_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-16-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_18_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-18-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_20_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-20-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_22_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-22-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_24_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-24-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_1_CPU_8_CORES = 'windows-server-2016-license-datacenter-edition-1-cpu-8-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_10_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-10-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_12_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-12-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_14_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-14-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_16_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-16-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_18_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-18-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_20_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-20-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_22_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-22-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_24_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-24-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_2_CPU_8_CORES = 'windows-server-2016-license-datacenter-edition-2-cpu-8-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_10_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-10-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_12_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-12-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_14_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-14-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_16_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-16-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_18_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-18-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_20_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-20-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_22_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-22-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_24_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-24-cores',
  WINDOWS_SERVER_2016_LICENSE_DATACENTER_EDITION_4_CPU_8_CORES = 'windows-server-2016-license-datacenter-edition-4-cpu-8-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_10_CORES = 'windows-server-2016-license-standard-edition-1-cpu-10-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_12_CORES = 'windows-server-2016-license-standard-edition-1-cpu-12-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_14_CORES = 'windows-server-2016-license-standard-edition-1-cpu-14-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_16_CORES = 'windows-server-2016-license-standard-edition-1-cpu-16-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_18_CORES = 'windows-server-2016-license-standard-edition-1-cpu-18-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_20_CORES = 'windows-server-2016-license-standard-edition-1-cpu-20-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_22_CORES = 'windows-server-2016-license-standard-edition-1-cpu-22-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_24_CORES = 'windows-server-2016-license-standard-edition-1-cpu-24-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_1_CPU_8_CORES = 'windows-server-2016-license-standard-edition-1-cpu-8-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_10_CORES = 'windows-server-2016-license-standard-edition-2-cpu-10-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_12_CORES = 'windows-server-2016-license-standard-edition-2-cpu-12-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_14_CORES = 'windows-server-2016-license-standard-edition-2-cpu-14-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_16_CORES = 'windows-server-2016-license-standard-edition-2-cpu-16-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_18_CORES = 'windows-server-2016-license-standard-edition-2-cpu-18-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_20_CORES = 'windows-server-2016-license-standard-edition-2-cpu-20-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_22_CORES = 'windows-server-2016-license-standard-edition-2-cpu-22-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_24_CORES = 'windows-server-2016-license-standard-edition-2-cpu-24-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_2_CPU_8_CORES = 'windows-server-2016-license-standard-edition-2-cpu-8-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_10_CORES = 'windows-server-2016-license-standard-edition-4-cpu-10-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_12_CORES = 'windows-server-2016-license-standard-edition-4-cpu-12-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_14_CORES = 'windows-server-2016-license-standard-edition-4-cpu-14-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_16_CORES = 'windows-server-2016-license-standard-edition-4-cpu-16-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_18_CORES = 'windows-server-2016-license-standard-edition-4-cpu-18-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_20_CORES = 'windows-server-2016-license-standard-edition-4-cpu-20-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_22_CORES = 'windows-server-2016-license-standard-edition-4-cpu-22-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_24_CORES = 'windows-server-2016-license-standard-edition-4-cpu-24-cores',
  WINDOWS_SERVER_2016_LICENSE_STANDARD_EDITION_4_CPU_8_CORES = 'windows-server-2016-license-standard-edition-4-cpu-8-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_10_CORES = 'windows-server-2019-license-datacenter-edition-10-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_12_CORES = 'windows-server-2019-license-datacenter-edition-12-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_14_CORES = 'windows-server-2019-license-datacenter-edition-14-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_16_CORES = 'windows-server-2019-license-datacenter-edition-16-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_18_CORES = 'windows-server-2019-license-datacenter-edition-18-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_20_CORES = 'windows-server-2019-license-datacenter-edition-20-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_22_CORES = 'windows-server-2019-license-datacenter-edition-22-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_24_CORES = 'windows-server-2019-license-datacenter-edition-24-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_26_CORES = 'windows-server-2019-license-datacenter-edition-26-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_28_CORES = 'windows-server-2019-license-datacenter-edition-28-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_30_CORES = 'windows-server-2019-license-datacenter-edition-30-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_32_CORES = 'windows-server-2019-license-datacenter-edition-32-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_34_CORES = 'windows-server-2019-license-datacenter-edition-34-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_36_CORES = 'windows-server-2019-license-datacenter-edition-36-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_38_CORES = 'windows-server-2019-license-datacenter-edition-38-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_40_CORES = 'windows-server-2019-license-datacenter-edition-40-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_42_CORES = 'windows-server-2019-license-datacenter-edition-42-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_44_CORES = 'windows-server-2019-license-datacenter-edition-44-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_46_CORES = 'windows-server-2019-license-datacenter-edition-46-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_48_CORES = 'windows-server-2019-license-datacenter-edition-48-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_50_CORES = 'windows-server-2019-license-datacenter-edition-50-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_52_CORES = 'windows-server-2019-license-datacenter-edition-52-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_54_CORES = 'windows-server-2019-license-datacenter-edition-54-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_56_CORES = 'windows-server-2019-license-datacenter-edition-56-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_58_CORES = 'windows-server-2019-license-datacenter-edition-58-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_60_CORES = 'windows-server-2019-license-datacenter-edition-60-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_62_CORES = 'windows-server-2019-license-datacenter-edition-62-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_64_CORES = 'windows-server-2019-license-datacenter-edition-64-cores',
  WINDOWS_SERVER_2019_LICENSE_DATACENTER_EDITION_8_CORES = 'windows-server-2019-license-datacenter-edition-8-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_10_CORES = 'windows-server-2019-license-standard-edition-10-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_12_CORES = 'windows-server-2019-license-standard-edition-12-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_14_CORES = 'windows-server-2019-license-standard-edition-14-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_16_CORES = 'windows-server-2019-license-standard-edition-16-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_18_CORES = 'windows-server-2019-license-standard-edition-18-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_20_CORES = 'windows-server-2019-license-standard-edition-20-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_22_CORES = 'windows-server-2019-license-standard-edition-22-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_24_CORES = 'windows-server-2019-license-standard-edition-24-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_26_CORES = 'windows-server-2019-license-standard-edition-26-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_28_CORES = 'windows-server-2019-license-standard-edition-28-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_30_CORES = 'windows-server-2019-license-standard-edition-30-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_32_CORES = 'windows-server-2019-license-standard-edition-32-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_34_CORES = 'windows-server-2019-license-standard-edition-34-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_36_CORES = 'windows-server-2019-license-standard-edition-36-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_38_CORES = 'windows-server-2019-license-standard-edition-38-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_40_CORES = 'windows-server-2019-license-standard-edition-40-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_42_CORES = 'windows-server-2019-license-standard-edition-42-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_44_CORES = 'windows-server-2019-license-standard-edition-44-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_46_CORES = 'windows-server-2019-license-standard-edition-46-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_48_CORES = 'windows-server-2019-license-standard-edition-48-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_50_CORES = 'windows-server-2019-license-standard-edition-50-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_52_CORES = 'windows-server-2019-license-standard-edition-52-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_54_CORES = 'windows-server-2019-license-standard-edition-54-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_56_CORES = 'windows-server-2019-license-standard-edition-56-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_58_CORES = 'windows-server-2019-license-standard-edition-58-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_60_CORES = 'windows-server-2019-license-standard-edition-60-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_62_CORES = 'windows-server-2019-license-standard-edition-62-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_64_CORES = 'windows-server-2019-license-standard-edition-64-cores',
  WINDOWS_SERVER_2019_LICENSE_STANDARD_EDITION_8_CORES = 'windows-server-2019-license-standard-edition-8-cores'
}

/*
 * All SQL Server versions for Windows products
 */
export enum LicenseWindowsSqlVersion {
  SQL_SERVER_2008_STANDARD_EDITION = 'SQL_SERVER_2008_STANDARD_EDITION',
  SQL_SERVER_2008_STANDARD_EDITION_2_CPU = 'SQL_SERVER_2008_STANDARD_EDITION_2_CPU',
  SQL_SERVER_2008_WEB_EDITION = 'SQL_SERVER_2008_WEB_EDITION',
  SQL_SERVER_2008_WEB_EDITION_2_CPU = 'SQL_SERVER_2008_WEB_EDITION_2_CPU',
  SQL_SERVER_2012_STANDARD_EDITION = 'SQL_SERVER_2012_STANDARD_EDITION',
  SQL_SERVER_2012_STANDARD_EDITION_12_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_12_CORES',
  SQL_SERVER_2012_STANDARD_EDITION_16_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_16_CORES',
  SQL_SERVER_2012_STANDARD_EDITION_18_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_18_CORES',
  SQL_SERVER_2012_STANDARD_EDITION_20_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_20_CORES',
  SQL_SERVER_2012_STANDARD_EDITION_24_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_24_CORES',
  SQL_SERVER_2012_STANDARD_EDITION_2_CPU = 'SQL_SERVER_2012_STANDARD_EDITION_2_CPU',
  SQL_SERVER_2012_STANDARD_EDITION_32_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_32_CORES',
  SQL_SERVER_2012_STANDARD_EDITION_4_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_4_CORES',
  SQL_SERVER_2012_STANDARD_EDITION_6_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_6_CORES',
  SQL_SERVER_2012_STANDARD_EDITION_8_CORES = 'SQL_SERVER_2012_STANDARD_EDITION_8_CORES',
  SQL_SERVER_2012_WEB_EDITION_12_CORES = 'SQL_SERVER_2012_WEB_EDITION_12_CORES',
  SQL_SERVER_2012_WEB_EDITION_16_CORES = 'SQL_SERVER_2012_WEB_EDITION_16_CORES',
  SQL_SERVER_2012_WEB_EDITION_18_CORES = 'SQL_SERVER_2012_WEB_EDITION_18_CORES',
  SQL_SERVER_2012_WEB_EDITION_20_CORES = 'SQL_SERVER_2012_WEB_EDITION_20_CORES',
  SQL_SERVER_2012_WEB_EDITION_24_CORES = 'SQL_SERVER_2012_WEB_EDITION_24_CORES',
  SQL_SERVER_2012_WEB_EDITION_32_CORES = 'SQL_SERVER_2012_WEB_EDITION_32_CORES',
  SQL_SERVER_2012_WEB_EDITION_4_CORES = 'SQL_SERVER_2012_WEB_EDITION_4_CORES',
  SQL_SERVER_2012_WEB_EDITION_6_CORES = 'SQL_SERVER_2012_WEB_EDITION_6_CORES',
  SQL_SERVER_2012_WEB_EDITION_8_CORES = 'SQL_SERVER_2012_WEB_EDITION_8_CORES'
}

/*
 * Detailed renewal type of a service
 */
export enum ServiceRenewalType {
  AUTOMATICFORCEDPRODUCT = 'automaticForcedProduct',
  AUTOMATICV2012 = 'automaticV2012',
  AUTOMATICV2014 = 'automaticV2014',
  AUTOMATICV2016 = 'automaticV2016',
  MANUAL = 'manual',
  ONESHOT = 'oneShot',
  OPTION = 'option'
}

/**
 * Map a possible renew for a specific service
 */
export interface ServiceRenewType {
  automatic: boolean
  deleteAtExpiration: boolean
  forced: boolean
  manualPayment?: boolean
  period?: number
}

/*
 * 
 */
export enum ServiceState {
  EXPIRED = 'expired',
  INCREATION = 'inCreation',
  OK = 'ok',
  PENDINGDEBT = 'pendingDebt',
  UNPAID = 'unPaid'
}

/*
 * All future uses you can provide for a service termination
 */
export enum ServiceTerminationFutureUse {
  NOT_REPLACING_SERVICE = 'NOT_REPLACING_SERVICE',
  OTHER = 'OTHER',
  SUBSCRIBE_AN_OTHER_SERVICE = 'SUBSCRIBE_AN_OTHER_SERVICE',
  SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR = 'SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR',
  SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR = 'SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR'
}

/*
 * All reasons you can provide for a service termination
 */
export enum ServiceTerminationReason {
  FEATURES_DONT_SUIT_ME = 'FEATURES_DONT_SUIT_ME',
  LACK_OF_PERFORMANCES = 'LACK_OF_PERFORMANCES',
  MIGRATED_TO_ANOTHER_OVH_PRODUCT = 'MIGRATED_TO_ANOTHER_OVH_PRODUCT',
  MIGRATED_TO_COMPETITOR = 'MIGRATED_TO_COMPETITOR',
  NOT_ENOUGH_RECOGNITION = 'NOT_ENOUGH_RECOGNITION',
  NOT_NEEDED_ANYMORE = 'NOT_NEEDED_ANYMORE',
  NOT_RELIABLE = 'NOT_RELIABLE',
  NO_ANSWER = 'NO_ANSWER',
  OTHER = 'OTHER',
  PRODUCT_DIMENSION_DONT_SUIT_ME = 'PRODUCT_DIMENSION_DONT_SUIT_ME',
  PRODUCT_TOOLS_DONT_SUIT_ME = 'PRODUCT_TOOLS_DONT_SUIT_ME',
  TOO_EXPENSIVE = 'TOO_EXPENSIVE',
  TOO_HARD_TO_USE = 'TOO_HARD_TO_USE',
  UNSATIFIED_BY_CUSTOMER_SUPPORT = 'UNSATIFIED_BY_CUSTOMER_SUPPORT'
}

/**
 * Details about a Service
 */
export interface ServicesService {
  canDeleteAtExpiration: boolean
  contactAdmin: string
  contactBilling: string
  contactTech: string
  creation: string
  domain: string
  engagedUpTo?: string
  expiration: string
  possibleRenewPeriod?: number[]
  renew?: ServiceRenewType
  renewalType: ServiceRenewalType
  serviceId: number
  status: ServiceState
}


export class LicenseWindows {
  constructor(private client: Client) {}

  /**
   * Operations about the LICENSE service [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows#GET)
   */
  ListAvailableServices(): Promise<string[]> {
    let url = `/license/windows`

    return this.client.request<string[]>('GET', url)
  }

  /**
   * Your Windows license [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D#GET)
   */
  GetThisObjectProperties(serviceName: string): Promise<LicensewindowsWindows> {
    let url = `/license/windows/${serviceName}`

    return this.client.request<LicensewindowsWindows>('GET', url)
  }

  /**
   * Your Windows license [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D#PUT)
   */
  AlterThisObjectProperties(serviceName: string, payload: LicensewindowsWindows): Promise<void> {
    let url = `/license/windows/${serviceName}`

    return this.client.request<void>('PUT', url, payload)
  }

  /**
   * Confirm termination of your service [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/confirmTermination#POST)
   */
  ConfirmTerminationOfYourService(serviceName: string, token: string, commentary?: string, futureUse?: ServiceTerminationFutureUse, reason?: ServiceTerminationReason): Promise<string> {
    let url = `/license/windows/${serviceName}/confirmTermination`

    return this.client.request<string>('POST', url, {token, commentary, futureUse, reason})
  }

  /**
   * List the license.Option objects [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/option#GET)
   */
  OptionsAttachedToThisLicense(serviceName: string): Promise<LicenseOptionLabel[]> {
    let url = `/license/windows/${serviceName}/option`

    return this.client.request<LicenseOptionLabel[]>('GET', url)
  }

  /**
   * Your License options [PRODUCTION]
  * [WARN] This API action is not ready (duplicate name)
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/option/%7Blabel%7D#GET)
   */
  /*
  GetThisObjectProperties(label: LicenseOptionLabel, serviceName: string): Promise<LicenseOption> {
    let url = `/license/windows/${serviceName}/option/${label}`

    return this.client.request<LicenseOption>('GET', url)
  }
  */

  /**
   * Your License options [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/option/%7Blabel%7D#DELETE)
   */
  ReleaseThisOption(label: LicenseOptionLabel, serviceName: string): Promise<LicenseTask> {
    let url = `/license/windows/${serviceName}/option/${label}`

    return this.client.request<LicenseTask>('DELETE', url)
  }

  /**
   * Details about a Service [PRODUCTION]
  * [WARN] This API action is not ready (duplicate name)
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/serviceInfos#GET)
   */
  /*
  GetThisObjectProperties(serviceName: string): Promise<ServicesService> {
    let url = `/license/windows/${serviceName}/serviceInfos`

    return this.client.request<ServicesService>('GET', url)
  }
  */

  /**
   * Details about a Service [PRODUCTION]
  * [WARN] This API action is not ready (duplicate name)
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/serviceInfos#PUT)
   */
  /*
  AlterThisObjectProperties(serviceName: string, payload: ServicesService): Promise<void> {
    let url = `/license/windows/${serviceName}/serviceInfos`

    return this.client.request<void>('PUT', url, payload)
  }
  */

  /**
   * sqlServer operations [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/sqlServer#POST)
   */
  LinkYourOwnSqlServerLicenseToThisWindowsLicense(licenseId: string, serviceName: string, version: LicenseWindowsSqlVersion): Promise<LicenseTask> {
    let url = `/license/windows/${serviceName}/sqlServer`

    return this.client.request<LicenseTask>('POST', url, {licenseId, version})
  }

  /**
   * List the license.Task objects [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/tasks#GET)
   */
  TasksLinkedToThisLicense(serviceName: string, action?: LicenseActionType, status?: LicenseTaskState): Promise<number[]> {
    let url = `/license/windows/${serviceName}/tasks?`

    const queryParams = new QueryParams()
    if (action) { queryParams.set('action', action.toString()) }
    if (status) { queryParams.set('status', status.toString()) }

    return this.client.request<number[]>('GET', url+queryParams.toString())
  }

  /**
   * licenses Todos [PRODUCTION]
  * [WARN] This API action is not ready (duplicate name)
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/tasks/%7BtaskId%7D#GET)
   */
  /*
  GetThisObjectProperties(serviceName: string, taskId: number): Promise<LicenseTask> {
    let url = `/license/windows/${serviceName}/tasks/${taskId}`

    return this.client.request<LicenseTask>('GET', url)
  }
  */

  /**
   * Terminate your service [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/%7BserviceName%7D/terminate#POST)
   */
  TerminateYourService(serviceName: string): Promise<string> {
    let url = `/license/windows/${serviceName}/terminate`

    return this.client.request<string>('POST', url)
  }

  /**
   * Get the orderable Windows versions [PRODUCTION]
   * [See on api.ovh.com](https://eu.api.ovh.com/console/#/license/windows/orderableVersions#GET)
   */
  GetTheOrderableWindowsVersions(ip: string): Promise<LicenseWindowsOrderConfiguration[]> {
    let url = `/license/windows/orderableVersions?`

    const queryParams = new QueryParams()
    if (ip) { queryParams.set('ip', ip.toString()) }

    return this.client.request<LicenseWindowsOrderConfiguration[]>('GET', url+queryParams.toString())
  }

}
